'open NADWGEO'
'run frame'
'set lat 40 90'
'set lon -60  0'
'set gxout grid'
'set digsize 0.15'
'set xlint 10'
'set mpdraw off'
'd geo'
'open geoall'
'set dfile 2'
'set lat 40 90'
'set lon -60  0'
'set z 10'
'set gxout fgrid'
'set fgvals 0 1'
'd geoall'
