'open HISTORY3'
'set grads off'
'set gxout contour'
'set font 1'
'set lat 0 72'
'set lev 0 3500'
'set yflip on'
'set x 1'
'set cint 1'
'set rbrange 10 25'
'd ave(tem,x=1,x=12)'
'open geo'
'set gxout grfill'
'set dfile 2'
'set lat 0 72'
'set lev 0 3500'
'set yflip on'
'set x 1'
'set t 1'
'run geopaint geo'
