for dirname in                                      \
  ADD ANN2CLIM_G ANN_ANOM BBL2BTM_T BBL2BTM_U BTSF  \
  COASTGRID CORE_6HR2MON CURLTAU CUT_OUT \
  DAY2ANN_G DAY2MON DAY2MONMAX DAY2MONMAX_YM DAY2MON_G DAY2MON_YM \
  DIVGTAU DIVICE \
  F6HR2MON FOURIER FOURIER2 FW_CONTENT  \
  GLB2RGN_IJ GLOBALMEAN GLOBALMEAN2D GLOBALMEAN3D \
  GM2MOC GM2MOCIP GM2WLWL  \
  GRD2NC_G HS2BIV HS2BTM_T HS2BTM_UV HS2MOC \
  HS2MOCIP HS2PRS HS2PV HS2UVMO HS2ZM HS2ZM_W HT_CONTENT \
  LNRCMB LOCALMEAN MAG_TAU MAP_SCALAR MAP_VECTOR MAXMIN_G \
  MKGRADS_FOR_TRUNK MKTABLE MOCIP2TRN MON2ANN MON2ANN_G \
  MONCLIM MONCLIM_G MON_ANOM MON_EKE MULTIPLY \
  NHT NST NWT OVERWRITE P2A_G PASSAGE PASSAGE_ICE \
  MASKOUT MASK_UV2TS R4_TO_R8 R8_TO_R4 REPLACE_RANGE \
  REGCOR REMAP_SCALAR REMAP_T REMAP_U REMAP_UV REMAP_VECTOR \
  REPLACE RESTART2RS RIVMOUTH2COAST RUNMEAN \
  SIGMA2MLD SPH_SCALE STDDEV \
  TOTAL_MOC TOTAL_TRNIP TS2DENSITY TS2SIGMA TS2STERIC TXT_TO_R4 \
  UV2W UV2WLWL UV2ZETA VERT_ADV VOLO XFACTOR XY2UV ZMMGRD ZOS WSPD
do
  echo ======= ${dirname} =======
  sed -f option.sed ${dirname}/Makefile.in > ${dirname}/Makefile
  cd ${dirname}/
  make
  make clean
  cd ../
done

